apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-practice-app
  labels:
    app: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: web-app
        image: ghcr.io/bmk3263/argo-practice-app:initial # GH Actions will overwrite this
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-practice-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gitops-app
